### ISSUE TITLE
mouse brain data

### ISSUE THREAD

**Issue by chenx9** [leonfodoulian/SARS_CoV_2_anosmia#2]
I was wondering how you analyzed the mouse brain data  in your article. I can't find the information.

**Comment by leonfodoulian** [comment]
Hi @chenx9,

We didn't re-analyse the data. We just generated the desired graphs from the corresponding websites. You can find that information in _Mouse brain cell database mining_ in the **Transparent Methods** section of the article.

Best,
Leon
